export const COORDINADORES = {
    "aldo.aliaga@entel.pe": "ALDO.ALIAGA",
    "melina.rojas@entel.pe": "ALICIA.ROJAS",
    "carolina.lazarte@entel.pe": "CAROLINA.LAZARTE",
    "cesar.guzman@entel.pe": "CESAR.GUZMAN",
    "christian.albujar@entel.pe": "CHRISTIAN.ALBUJAR",
    "eduardo.rodriguez@entel.pe": "EDUARDO.RODRIGUEZ" ,
    "erick.japay@entel.pe": "ERICK.JAPAY",
    "everaldo.ccopa@entel.pe": "EVERALDO.CCOPA", 
    "ilianis.graterol@entel.pe": "ILIANIS.GRATEROL", 
    "jennifer.cotos@entel.pe": "JENNIFER.COTOS",
    "john.artica@entel.pe": "JOHN.ARTICA",
    "jose.arroyo@entel.pe": "JOSE.ARROYO", 
    "ricardo.bazan@entel.pe": "JOSE.BAZAN",
    "juan.linares@entel.pe": "JUAN.LINARES", 
    "karina.tasayco@entel.pe": "KARINA.TASAYCO",
    "marco.suclupe@entel.pe": "MARCO.A.SUCLUPE", 
    "mariela.paredes@entel.pe": "MARIELA.PAREDES",
    "mario.montejos@entel.pe": "MARIO.MONTEJOS",
    "omar.escurra@entel.pe": "OMAR.ESCURRA",
    "patricia.arredondo@entel.pe": "PATRICIA.ARREDONDO", 
    "rafael.quintana@entel.pe": "RAFAEL.QUINTANA",
    "rodolfo.barreto@entel.pe": "RODOLFO.BARRETO",
    "ronald.buendia@entel.pe": "RONALD.BUENDIA",
    "walter.chilon@entel.pe": "WALTER.CHILON",
    "yuliana.herrera@entel.pe": "YULIANA.HERRERA", 
    "fabian.huapaya@entel.pe": "FABIAN.HUAPAYA",
    "gloria.perez@entel.pe": "GLORIA.PEREZ",
    "katerin.delacruz@entel.pe": "KATERIN.DELACRUZ",
    "katia.chumpitaz@entel.pe": "KATIA.CHUMPITAZ",
    "manuel.luna@entel.pe": "MANUEL.LUNA",
    "juan.caldas@entel.pe": "JUAN.CALDAS",
    "juan.carlos.pena@entel.pe": "JUAN.PENA",
    "victor.caballero@entel.pe": "VICTOR.CABALLERO", 
    "carlos.gallardo@entel.pe": "CARLOS.GALLARDO",
    "ricardo.zunini@entel.pe": "RICARDO.ZUNINI",
    "elizabeth.sanchez@entel.pe": "ELIZABETH.SANCHEZ", 
}

export const COORDINADORES_REAL = [
    { name: "ALDO.ALIAGA", email: "aldo.aliaga@entel.pe" },
    { name: "ALICIA.ROJAS", email: "melina.rojas@entel.pe" },
    { name: "CAROLINA.LAZARTE", email: "carolina.lazarte@entel.pe" },
    { name: "CESAR.GUZMAN", email: "cesar.guzman@entel.pe" },
    { name: "CHRISTIAN.ALBUJAR", email: "christian.albujar@entel.pe" },
    { name: "EDUARDO.RODRIGUEZ", email: "eduardo.rodriguez@entel.pe" },
    { name: "ERICK.JAPAY", email: "erick.japay@entel.pe" },
    { name: "EVERALDO.CCOPA", email: "everaldo.ccopa@entel.pe" },
    { name: "ILIANIS.GRATEROL", email: "ilianis.graterol@entel.pe" },
    { name: "JENNIFER.COTOS", email: "jennifer.cotos@entel.pe" },
    { name: "JOHN.ARTICA", email: "john.artica@entel.pe" },
    { name: "JOSE.ARROYO", email: "jose.arroyo@entel.pe" },
    { name: "JOSE.BAZAN", email: "ricardo.bazan@entel.pe" },
    { name: "JUAN.LINARES", email: "juan.linares@entel.pe" },
    { name: "KARINA.TASAYCO", email: "karina.tasayco@entel.pe" },
    { name: "MARCO.A.SUCLUPE", email: "marco.suclupe@entel.pe" },
    { name: "MARIELA.PAREDES", email: "mariela.paredes@entel.pe" },
    { name: "MARIO.MONTEJOS", email: "mario.montejos@entel.pe" },
    { name: "OMAR.ESCURRA", email: "omar.escurra@entel.pe" },
    { name: "PATRICIA.ARREDONDO", email: "patricia.arredondo@entel.pe" },
    { name: "RAFAEL.QUINTANA", email: "rafael.quintana@entel.pe" },
    { name: "RODOLFO.BARRETO", email: "rodolfo.barreto@entel.pe" },
    { name: "RONALD.BUENDIA", email: "ronald.buendia@entel.pe" },
    { name: "WALTER.CHILON", email: "walter.chilon@entel.pe" },
    { name: "YULIANA.HERRERA", email: "yuliana.herrera@entel.pe" },
    { name: "FABIAN.HUAPAYA", email: "fabian.huapaya@entel.pe" },
    { name: "GLORIA.PEREZ", email: "gloria.perez@entel.pe" },
    { name: "KATERIN.DELACRUZ", email: "katerin.delacruz@entel.pe" },
    { name: "KATIA.CHUMPITAZ", email: "katia.chumpitaz@entel.pe" },
    { name: "MANUEL.LUNA", email: "manuel.luna@entel.pe" },
    { name: "JUAN.CALDAS", email: "juan.caldas@entel.pe" },
    { name: "JUAN.PENA", email: "juan.carlos.pena@entel.pe" },
    { name: "VICTOR.CABALLERO", email: "victor.caballero@entel.pe" },
    { name: "CARLOS.GALLARDO", email: "carlos.gallardo@entel.pe" },
    { name: "RICARDO.ZUNINI", email: "ricardo.zunini@entel.pe" },
    { name: "MIGUEL.DELOSSANTOS", email: "miguel.delossantos@entel.pe" },
    { name: "ELIZABETH.SANCHEZ", email: "elizabeth.sanchez@entel.pe" },

    // EXT
    { name: "ERNESTO.PAITAN", email: "epaitan@olitel.pe" },
    { name: "FERNANDO.COHARA", email: "fernando.cohara.ent@viaexperis2.pe" },
    { name: "A.ALDANA", email: "aaldanac@olitel.pe"}
]

export const UNIDADES_FUNCIONALES = {
    
    // Proyectos Outdoor
    "juan.caldas@entel.pe": "Proyectos Outdoor",
    "marco.suclupe@entel.pe": "Proyectos Outdoor",
    "cesar.avendano@entel.pe": "Proyectos Outdoor",
    "sebastian.berru@entel.pe": "Proyectos Outdoor",
    
    "aldo.aliaga@entel.pe": "Proyectos Outdoor",
    "christian.albujar@entel.pe": "Proyectos Outdoor",
    "epaitan@olitel.pe": "Proyectos Outdoor",
    "aaldanac@olitel.pe": "Proyectos Outdoor",
    "gloria.perez@entel.pe": "Proyectos Outdoor",
    "john.artica@entel.pe": "Proyectos Outdoor",
    "jose.arroyo@entel.pe": "Proyectos Outdoor",
    "katerin.delacruz@entel.pe": "Proyectos Outdoor",
    
    "katia.chumpitaz@entel.pe": "Proyectos Outdoor",
    "omar.escurra@entel.pe": "Proyectos Outdoor",
    "rafael.quintana@entel.pe": "Proyectos Outdoor",
    "ricardo.bazan@entel.pe": "Proyectos Outdoor",
    "rodolfo.barreto@entel.pe": "Proyectos Outdoor",
    "ronald.buendia@entel.pe": "Proyectos Outdoor",
    "elizabeth.sanchez@entel.pe": "Proyectos Outdoor",

    "internal_master@entel.pe": "Proyectos Outdoor",
    "testing2@entel.pe": "Transporte e Indoor",

    // Facilities
    "juan.castro@entel.pe": "Facilities e Infraestructura Critica",
    "walter.chilon@entel.pe": "Facilities e Infraestructura Critica",
    "eduardo.rodriguez@entel.pe": "Facilities e Infraestructura Critica",
    "mario.montejos@entel.pe": "Facilities e Infraestructura Critica",
    "juan.linares@entel.pe": "Facilities e Infraestructura Critica",
    "manuel.luna@entel.pe": "Facilities e Infraestructura Critica",

    // Transporte
    "yuliana.herrera@entel.pe": "Transporte e Indoor",
    "miguel.delossantos@entel.pe": "Transporte e Indoor",
    "fabian.huapaya@entel.pe": "Transporte e Indoor",
    "ilianis.graterol@entel.pe": "Transporte e Indoor",
    "everaldo.ccopa@entel.pe": "Transporte e Indoor",
    "carolina.lazarte@entel.pe": "Transporte e Indoor",
    "juan.carlos.pena@entel.pe": "Transporte e Indoor",
    "melina.rojas@entel.pe": "Transporte e Indoor",
    "victor.caballero@entel.pe": "Transporte e Indoor",
    "brenda.osorio.ent@viaexperis2.pe": "Transporte e Indoor",
    "mcachay@olitel.pe": "Transporte e Indoor",
    "marco.alvaro.ent@viaexperis2.pe": "Transporte e Indoor",
    "medelein.tapia@entel.pe": "Transporte e Indoor",

    // Administracion de Sitios
    "karina.tasayco@entel.pe": "Administracion de Sitios",
    "patricia.arredondo@entel.pe": "Administracion de Sitios"
}