export const PERMS = {
    "PROJECTS": {
        "PROJECT_WORKFLOW_PM_ADMIN_FUNCTIONS": "PROJECT_WORKFLOW_PM_ADMIN_FUNCTIONS",
    },
    "BUDGET": {
        "BUDGET_MODULE_ACCESS": "BUDGET_MODULE_ACCESS",
        "CAPEX_MODULE_ACCESS": "CAPEX_MODULE_ACCESS",
        "CAPEX_DASHBOARD_READ": "CAPEX_DASHBOARD_READ",
        "CAPEX_EXECUTION_READ": "CAPEX_EXECUTION_READ",
        "CAPEX_PM_READ": "CAPEX_PM_READ",
        "CAPEX_LEADERSHIP_READ": "CAPEX_LEADERSHIP_READ",
        "CAPEX_RQ_READ": "CAPEX_RQ_READ",
        "CAPEX_CR_READ": "CAPEX_CR_READ",
        "CAPEX_FORECASTS_READ": "CAPEX_FORECASTS_READ",
        "CAPEX_UPLOAD_READ": "CAPEX_UPLOAD_READ",
        "OPEX_MODULE_ACCESS": "OPEX_MODULE_ACCESS",
        "OPEX_DASHBOARD_READ": "OPEX_DASHBOARD_READ",
        "OPEX_SCENARIOS_READ": "OPEX_SCENARIOS_READ",
        "OPEX_LEASES_READ": "OPEX_LEASES_READ",
        "OPEX_UPLOAD_READ": "OPEX_UPLOAD_READ",
        "REQUERIMIENTO_MODULE_ACCESS": "REQUERIMIENTO_MODULE_ACCESS",
        "REQUERIMIENTO_DASHBOARD_REQ_READ": "REQUERIMIENTO_DASHBOARD_REQ_READ",
        "REQUERIMIENTO_SUMMARY_READ": "REQUERIMIENTO_SUMMARY_READ",
        "REQUERIMIENTO_TICKETS_READ": "REQUERIMIENTO_TICKETS_READ",
        "REQUERIMIENTO_TICKETS_CREATE": "REQUERIMIENTO_TICKETS_CREATE",
        "REQUERIMIENTO_TICKETS_DELETE": "REQUERIMIENTO_TICKETS_DELETE",
        "REQUERIMIENTO_TICKETS_UPDATE": "REQUERIMIENTO_TICKETS_UPDATE",
        "REQUERIMIENTO_TICKETS_READ_ALL_TICKETS": "REQUERIMIENTO_TICKETS_READ_ALL_TICKETS",
        "REQUERIMIENTO_TICKETS_READ_ALL_SITES": "REQUERIMIENTO_TICKETS_READ_ALL_SITES",
        "REQUERIMIENTO_TICKETS_UPDATE_MASTER": "REQUERIMIENTO_TICKETS_UPDATE_MASTER",
        "REQUERIMIENTO_TICKETS_UPDATE_USER": "REQUERIMIENTO_TICKETS_UPDATE_USER",
        "REQUERIMIENTO_PAYMENTS_READ": "REQUERIMIENTO_PAYMENTS_READ",
        "REQUERIMIENTO_PAYMENTS_READ_ALL": "REQUERIMIENTO_PAYMENTS_READ_ALL",

        // SETTLEMENTS
        "REQUERIMIENTO_SETTLEMENTS_READ": "REQUERIMIENTO_SETTLEMENTS_READ",
        "REQUERIMIENTO_SETTLEMENTS_READ_ALL": "REQUERIMIENTO_SETTLEMENTS_READ_ALL",
        "REQUERIMIENTO_SETTLEMENTS_READ_ALL_INTERNAL": "REQUERIMIENTO_SETTLEMENTS_READ_ALL_INTERNAL",

        // DELIVERABLES
        "REQUERIMIENTO_DELIVERABLES_READ": "REQUERIMIENTO_DELIVERABLES_READ",
        "REQUERIMIENTO_DELIVERABLES_READ_ALL": "REQUERIMIENTO_DELIVERABLES_READ_ALL",

        "REQUERIMIENTO_PA_READ": "REQUERIMIENTO_PA_READ",
    }
}